### ISSUE TITLE
raise StopIteration in 25 epoch

### ISSUE THREAD

**Issue by github-lpw** [CSAILVision/semantic-segmentation-pytorch#101]
The program would raise StopIteration in 25 epoch whatever the number of epoch I set(50,100 etc). 

The  error detail: 
Epoch: [25][4980/5000], Time: 1.00, Data: 0.01, lr_encoder: 0.015439, lr_decoder: 0.015439, Accuracy: 96.66, Loss: 0.142985
Saving checkpoints...
Traceback (most recent call last):
  File "train.py", line 317, in <module>
    main(args)
  File "train.py", line 200, in main
    train(segmentation_module, iterator_train, optimizers, history, epoch, args)
  File "train.py", line 31, in train
    batch_data = next(iterator)
  File "/mnt/lustre/linpeiwen/game/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 273, in __next__
    raise StopIteration
StopIteration

**Comment by ZwwWayne** [comment]
I meet the same problem.
When I set the iteration num to be 1264 for each epoch, it stop after showing  1120th outcome at 99th epoch, and if it is 1263, it stop after showing 1220th outcome at 99th epoch.
So it seems it will always stop at the 125000th iteration for some reason, but I do not know why.

**Comment by Tete-Xiao** [comment]
It's because we use a fake size of dataset for dataloader.

Just increasing the previous fake size, and it should be good then.
