### ISSUE TITLE
feed_dict in models/models.py is  list instead of a dict

### ISSUE THREAD

**Issue by Air-Fighter** [CSAILVision/semantic-segmentation-pytorch#103]
When I try to run **train.py**, it raises the following error:

> TypeError: list indices must be integers or slices, not str

It seems that the **feed_dict** is a list instead of a dict.

And, when I run **train.py** on GPU (mine is Titan Xp), I need to change all the **feed_dict['*']** to **feed_dict[0]['*'].cuda()** to make it work.

**Comment by Air-Fighter** [comment]
BTW, there is nothing wrong in inference. This puzzles me.

**Comment by Tete-Xiao** [comment]
I suppose you're using a single GPU to train the network.
It's a little tricky to modify the codes, but it should be fine if you're using multiple GPUs.

**Comment by Air-Fighter** [comment]
Yes, you're right. Single GPU is not the key, but the limited memery size of GPU causes this error.

Once I train the model on a single GPU with >12GB memory, the problem disappears.
