### ISSUE TITLE
From which paper is the UPerNet architecture taken?

### ISSUE THREAD

**Issue by jackaceuser** [CSAILVision/semantic-segmentation-pytorch#105]
Hi
I was wondering from which paper the UPerNet architecture is taken?
I'm looking for the paper that describes it, and the reasoning behind it.

Thanks

**Comment by hangzhaomit** [comment]
@jackaceuser 
Unified Perceptual Parsing for Scene Understanding. T. Xiao, Y. Liu, B. Zhou, Y. Jiang, and J. Sun.
