### ISSUE TITLE
intersectionAndUnion

### ISSUE THREAD

**Issue by nobinov** [CSAILVision/semantic-segmentation-pytorch#106]
https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/24e13b30f1af9f8ae7fb80b5cace899be3d1794a/utils.py#L116

In contrast to the comment the unlabeled pixels are not ignored. The line has no effect other than potentially changing the shape of pred. At least that is how it played out when we were trying to use the function in our context. Cheers

**Comment by Tete-Xiao** [comment]
I think you need to go through the codes more carefully. First, before line 112, the imPred is in [0, 149]. Here it's in [1, 150], and after line 116, the ignored region would be set to 0. Later the histogram ignores the region with label 0.
