### ISSUE TITLE
cuda runtime error (59) when using my own data

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [CSAILVision/semantic-segmentation-pytorch#107]
As I want to train model on my own data, I generate new *.odgt* files by replacing the paths of train/val images. It looks like:

> {"fpath_segm": "label_ade_format/val/121/72.png", "fpath_img": "src/val/121/72.jpg", "height": 1658, "width": 851}

Also, I transform my annotation images into *png* format like ADE. However, the following error raised:

> /pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [0,0,0], thread: [381,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [0,0,0], thread: [382,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [0,0,0], thread: [383,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    main(args)
  File "train.py", line 200, in main
    train(segmentation_module, iterator_train, optimizers, history, epoch, args)
  File "train.py", line 37, in train
    loss, acc = segmentation_module(batch_data)
  File "/home/xxx/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/GitWS/semantic-segmentation-pytorch/models/models.py", line 38, in forward
    loss_deepsup = self.crit(pred_deepsup, feed_dict[0]['seg_label'].cuda())
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorCopy.cpp:21

Do you have any idea about the cause of this error?

**Comment by Air-Fighter** [comment]
After *pdb* the code, I found that the **'seg_label'** becomes something like

> tensor([[[ -1,  -1,  -1,  ...,  -1,  -1,  -1],
         [ -1,  -1,  -1,  ...,  -1,  -1,  -1],
         [ -1,  -1,  -1,  ...,  -1,  -1,  -1],
         ...,
         [ -1,  -1,  -1,  ...,  -1,  -1,  -1],
         [ -1,  -1,  -1,  ...,  -1,  -1,  -1],
         [ -1,  -1,  -1,  ...,  -1,  -1,  -1]],

        [[ -1,  -1,  -1,  ...,  -1,  -1,  -1],
         [ -1,  -1,  -1,  ...,  -1,  -1,  -1],
         [ -1,  -1,  -1,  ...,  -1,  -1,  -1],
         ...,
         [ -1,  -1,  -1,  ...,  -1,  -1,  -1],
         [ -1,  -1,  -1,  ...,  -1,  -1,  -1],
         [ -1,  -1,  -1,  ...,  -1,  -1,  -1]]])

However, I didn't change the code of preprocessing, how does this happen?

**Comment by Air-Fighter** [comment]
Now, the interesting thing is that the code runs well in first **iteration**, however it still breaks down in the following iterations and raises same error as above.

**Comment by Air-Fighter** [comment]
It seems that the cause of the problem has changed. Now, the traceback is:

```
Traceback (most recent call last):
  File "train.py", line 319, in <module>
    main(args)
  File "train.py", line 205, in main
    train(segmentation_module, iterator_train, optimizers, history, epoch, args)
  File "train.py", line 42, in train
    loss, acc = segmentation_module(batch_data)
  File "/home/xxx/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/GitWS/semantic-segmentation-pytorch/models/models.py", line 54, in forward
    print(pred, file=debug_file)
  File "/home/xxx/.local/lib/python3.5/site-packages/torch/tensor.py", line 57, in __repr__
    return torch._tensor_str._str(self)
  File "/home/xxx/.local/lib/python3.5/site-packages/torch/_tensor_str.py", line 256, in _str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/xxx/.local/lib/python3.5/site-packages/torch/_tensor_str.py", line 82, in __init__
    copy = torch.empty(tensor.size(), dtype=torch.float64).copy_(tensor).view(tensor.nelement())
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorCopy.cpp:70

**Comment by gemfield** [comment]
t >= 0 && t < n_classes means the max number in annotation png files is greater/euqal than num_classes.
