### ISSUE TITLE
Support for non CUDA machines

### ISSUE THREAD

**Issue by divyanshumehta** [CSAILVision/semantic-segmentation-pytorch#117]
Thanks in Advance. The work you people have done is awesome btw.

Well I read that the code development environment was with 2-8 graphics memory. But is there a way of just running the visualisation of a non CUDA device, so that i could use it for doing segmentation on client devices.

**Comment by hangzhaomit** [comment]
Yes you could take away .cuda() and .to(device) in the code, so that you just run on cpu.

**Comment by nefelipk** [comment]
Hello,

When I do not change anything in test.py I get this error:
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

When I comment the lines 
76. torch.cuda.set_device(args.gpu) (or give as argument -1)
108. segmentation_module.cuda()
I get the error:
AssertionError: Torch not compiled with CUDA enabled

I also did not find .to(device) anywhere in the code.

Could you please share how you fix these problems and run on a non CUDA device?

Thank you very much in advance.
