### ISSUE TITLE
'async' is a reserved word in Python >= 3.7

### ISSUE THREAD

**Issue by cclauss** [CSAILVision/semantic-segmentation-pytorch#125]
Same issue and solution as CSAILVision/IBD#1

[flake8](http://flake8.pycqa.org) testing of https://github.com/CSAILVision/semantic-segmentation-pytorch on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/nn/parallel/data_parallel.py:16:31: E999 SyntaxError: invalid syntax
        v = obj.cuda(dev, async=True)
                              ^
./models/models.py:172:27: F821 undefined name 'UPerNetTmp'
            net_decoder = UPerNetTmp(
                          ^
1     E999 SyntaxError: invalid syntax
1     F821 undefined name 'UPerNetTmp'
2
```

**Comment by hangzhaomit** [comment]
Thanks for raising this issue. Can you send a PR? Thanks! @cclauss
