### ISSUE TITLE
fc_dim parameter not used for encoder

### ISSUE THREAD

**Issue by heinzermch** [CSAILVision/semantic-segmentation-pytorch#130]
Recently I was trying to decrease the size of the latent space of your models, which I suppose should be achieved by setting the value of the parameter fc_dim to something lower than 2048. However it seems that the option is currently not implemented for the encoder.

I know this is not an easy task, as any change in the latent space (number of channels) will break compatibility with the pre-trained ResNet models.

Any good ideas on how to implement this?

**Comment by hangzhaomit** [comment]
I think it is not very easy. Why not using ResNet18 directly, which has fc_dim=512?

**Comment by seedlit** [comment]
What is the meaning of the parameter 'fc_dim'?
