### ISSUE TITLE
Jobs stop after random iterations without any error information.

### ISSUE THREAD

**Issue by PkuRainBow** [CSAILVision/semantic-segmentation-pytorch#133]
I have implemented my method based on the code base.

I try to train my model from scratch and find that the jobs always stop outputting any log information after
a random number of iterations, and it is no more than one epoch over all the data.

For example, the job ended without updating the log information and without releasing the GPU memory.

```
Epoch: [1][4517/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019349, lr_decoder: 0.019349, Accuracy: 62.36, Loss: 2.131847
Epoch: [1][4518/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019348, lr_decoder: 0.019348, Accuracy: 62.37, Loss: 2.131737
Epoch: [1][4519/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019348, lr_decoder: 0.019348, Accuracy: 62.37, Loss: 2.131553
Epoch: [1][4520/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019348, lr_decoder: 0.019348, Accuracy: 62.37, Loss: 2.131408
Epoch: [1][4521/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019348, lr_decoder: 0.019348, Accuracy: 62.37, Loss: 2.131315
Epoch: [1][4522/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019348, lr_decoder: 0.019348, Accuracy: 62.37, Loss: 2.131346
Epoch: [1][4523/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019348, lr_decoder: 0.019348, Accuracy: 62.37, Loss: 2.131252
Epoch: [1][4524/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019347, lr_decoder: 0.019347, Accuracy: 62.37, Loss: 2.131484
Epoch: [1][4525/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019347, lr_decoder: 0.019347, Accuracy: 62.37, Loss: 2.131410
Epoch: [1][4526/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019347, lr_decoder: 0.019347, Accuracy: 62.37, Loss: 2.131326
Epoch: [1][4527/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019347, lr_decoder: 0.019347, Accuracy: 62.37, Loss: 2.131221
Epoch: [1][4528/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019347, lr_decoder: 0.019347, Accuracy: 62.37, Loss: 2.131181
Epoch: [1][4529/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019347, lr_decoder: 0.019347, Accuracy: 62.37, Loss: 2.131092
Epoch: [1][4530/5000], Time: 2.27, Data: 0.01, lr_encoder: 0.019347, lr_decoder: 0.019347, Accuracy: 62.38, Loss: 2.130914
```

**Comment by CWanli** [comment]
I have the same problem when I use my own net decoder but the GPU memory overflow is not happen obviously.
Epoch: [1][0/5000], Time: 18.08, Data: 0.60, lr_encoder: 0.010000, lr_decoder: 0.010000, Accuracy: 0.33, Loss: 5.688220
Epoch: [1][20/5000], Time: 2.45, Data: 0.15, lr_encoder: 0.009999, lr_decoder: 0.009999, Accuracy: 38.99, Loss: 3.154477
Epoch: [1][40/5000], Time: 2.07, Data: 0.14, lr_encoder: 0.009998, lr_decoder: 0.009998, Accuracy: 45.25, Loss: 2.650526
Epoch: [1][60/5000], Time: 1.94, Data: 0.14, lr_encoder: 0.009996, lr_decoder: 0.009996, Accuracy: 48.97, Loss: 2.386597
Epoch: [1][80/5000], Time: 1.88, Data: 0.14, lr_encoder: 0.009995, lr_decoder: 0.009995, Accuracy: 51.55, Loss: 2.213492
Epoch: [1][100/5000], Time: 1.84, Data: 0.14, lr_encoder: 0.009994, lr_decoder: 0.009994, Accuracy: 53.22, Loss: 2.109878
Epoch: [1][120/5000], Time: 1.82, Data: 0.13, lr_encoder: 0.009993, lr_decoder: 0.009993, Accuracy: 54.43, Loss: 2.033326
Epoch: [1][140/5000], Time: 1.80, Data: 0.13, lr_encoder: 0.009992, lr_decoder: 0.009992, Accuracy: 55.34, Loss: 1.963927
Epoch: [1][160/5000], Time: 1.78, Data: 0.13, lr_encoder: 0.009990, lr_decoder: 0.009990, Accuracy: 56.21, Loss: 1.908795
Epoch: [1][180/5000], Time: 1.77, Data: 0.13, lr_encoder: 0.009989, lr_decoder: 0.009989, Accuracy: 56.75, Loss: 1.864906
Epoch: [1][200/5000], Time: 1.75, Data: 0.13, lr_encoder: 0.009988, lr_decoder: 0.009988, Accuracy: 57.28, Loss: 1.826131
Epoch: [1][220/5000], Time: 1.75, Data: 0.13, lr_encoder: 0.009987, lr_decoder: 0.009987, Accuracy: 57.80, Loss: 1.793691
Epoch: [1][240/5000], Time: 1.74, Data: 0.13, lr_encoder: 0.009986, lr_decoder: 0.009986, Accuracy: 58.26, Loss: 1.764425
Epoch: [1][260/5000], Time: 1.73, Data: 0.13, lr_encoder: 0.009984, lr_decoder: 0.009984, Accuracy: 58.68, Loss: 1.739735
Epoch: [1][280/5000], Time: 1.72, Data: 0.13, lr_encoder: 0.009983, lr_decoder: 0.009983, Accuracy: 59.15, Loss: 1.711471


+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:04:00.0 Off |                  Off |
| N/A   32C    P0    51W / 250W |  12375MiB / 24445MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:06:00.0 Off |                  Off |
| N/A   32C    P0    49W / 250W |  13749MiB / 24445MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 00000000:0C:00.0 Off |                  Off |
| N/A   40C    P0    50W / 250W |  13443MiB / 24445MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           Off  | 00000000:0F:00.0 Off |                  Off |
| N/A   34C    P0    50W / 250W |  11029MiB / 24445MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by PkuRainBow** [comment]
@CWanli I also meet this problem when using my decoder.

I guess there exist some bugs within the current implementations. Maybe it is the problem with the sync-bn.

**Comment by hangzhaomit** [comment]
@PkuRainBow Did you use SyncBN in your own model?

**Comment by PkuRainBow** [comment]
@hangzhaomit Yes, I use the SyncBN to implement the OCNet based on your code base, and I have met this problem for multiple times.

**Comment by dekura** [comment]
I meet this problem too

**Comment by hangzhaomit** [comment]
@dekura @PkuRainBow 
Most likely it is GPU memory overflow. Please try to train with smaller images.

**Comment by sunpeng1996** [comment]
I also meet the problem? How do you deal with it?
