### ISSUE TITLE
dimension mismatch

### ISSUE THREAD

**Issue by johnathanchiu** [CSAILVision/semantic-segmentation-pytorch#138]
I got this error

RuntimeError: Given groups=1, weight of size [512, 320, 1, 1], expected input[1, 2048, 1, 1] to have 320 channels, but got 2048 channels instead

I saw the other thread and I tried changing it to 512 but it still didn't work

**Comment by hangzhaomit** [comment]
Can you let me know the command you are running?

**Comment by johnathanchiu** [comment]
I'm running through PyCharm but here are my defaults:

<img width="633" alt="screen shot 2018-12-30 at 6 03 06 pm" src="https://user-images.githubusercontent.com/43973975/50553517-2abc8300-0c5d-11e9-8f8f-63ef42dd67b3.png">

**Comment by johnathanchiu** [comment]
I used the default. This is the new error I got:

RuntimeError: Error(s) in loading state_dict for PPMDeepsup:
	size mismatch for cbr_deepsup.0.weight: copying a param with shape torch.Size([80, 160, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 1024, 3, 3]).
	size mismatch for cbr_deepsup.1.weight: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for cbr_deepsup.1.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for cbr_deepsup.1.running_mean: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for cbr_deepsup.1.running_var: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for cbr_deepsup.1._tmp_running_mean: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for cbr_deepsup.1._tmp_running_var: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for conv_last_deepsup.weight: copying a param with shape torch.Size([150, 80, 1, 1]) from checkpoint, the shape in current model is torch.Size([150, 512, 1, 1]).

**Comment by hangzhaomit** [comment]
What command are you running?

**Comment by johnathanchiu** [comment]
I'm not running any specific commands, I'm just using the defaults on pycharm. Should I run it from my terminal using the commands in the readme?

**Comment by hangzhaomit** [comment]
yes

**Comment by johnathanchiu** [comment]
I did everything from the readme. Still getting the same error not quite sure what's going wrong. I didn't change any dimensions. I'm running this bash command:

python3 -u test.py \
  --model_path /Users/[User]/Downloads/semantic-segmentation-pytorch-master-3/baseline-resnet50dilated-ppm_deepsup \
  --test_imgs /Users/[User]/Downloads/IMG_0106.jpeg \
  --arch_encoder resnet50dilated \
  --arch_decoder ppm_deepsup

**Comment by hangzhaomit** [comment]
If you are able to run the quick start ```./demo_test.sh```, then your setup should be correct.
