### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by IConquer96** [CSAILVision/semantic-segmentation-pytorch#151]
at first ,it's ok,then it happen this
RuntimeError: CUDA out of memory. Tried to allocate 4.46 GiB (GPU 0; 7.93 GiB total capacity; 4.72 GiB already allocated; 2.41 GiB free; 11.21 MiB cached)
but the nvidia-smi did not show the used,it's all free,could you help me?

**Comment by shlykov2** [comment]
whats your batch_size and what about gpus?

**Comment by hangzhaomit** [comment]
@IConquer96 Try to train with smaller image sizes.
