### ISSUE TITLE
Pretrained model on cpu only

### ISSUE THREAD

**Issue by nefelipk** [CSAILVision/semantic-segmentation-pytorch#153]
Hello,

I tried what @hangzhaomit suggested to be able to run on cpu, but it didn't work.

When I do not change anything in test.py I get this error:
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

When I comment the lines 
76. torch.cuda.set_device(args.gpu) (or give as argument -1)
108. segmentation_module.cuda()
I get the error:
AssertionError: Torch not compiled with CUDA enabled

I also did not find .to(device) anywhere in the code.

Could you please share how you fix these problems and run on a non CUDA device?

Thank you very much in advance.

_Originally posted by @nefelipk in https://github.com/CSAILVision/semantic-segmentation-pytorch/issues/117#issuecomment-475057813_

**Comment by Songloading** [comment]
Hi, did you solve this problem?

**Comment by tejaswigowda** [comment]
Can you please help with this?

**Comment by tejaswigowda** [comment]
Works! Thanks so much for your work.

**Comment by Ma4ria** [comment]
Hi, how did you solve this problem? I am having the same issue

**Comment by tejaswigowda** [comment]
CPU-only solution: https://github.com/tejaswigowda/semseg-pytorch

**Comment by Muratoter** [comment]
@tejaswigowda  Model run with GPU took 3 sec, but CPU takes 30 sec around. Is that normal?
