### ISSUE TITLE
Args about training the model to my data

### ISSUE THREAD

**Issue by HazelHik** [CSAILVision/semantic-segmentation-pytorch#156]
Hi, I'm new to the semantic segmentation area and pytorch, thank you for sharing the code.

I want to use the model for other data but I'm not so sure about the input args, what does imgSize mean? (the default is [300, 375, 450, 525, 600])
For example, my data is all of 800 * 600, how should I change the parameters?

Thanks!

**Comment by shlykov2** [comment]
[600, 800]

**Comment by komms** [comment]
As far as I know they all are kind of FCN's (Fully Convolutional Networks). There are no fully connected layers. So any image size is possible given that your GPU has sufficient memory. But there is a limitation in Max imageSize fro different models, follow accordingly

**Comment by hangzhaomit** [comment]
@HazelHik 
As @komms mentioned, any size is ok, as long as they are not too big (exceeding gpu memory limit).
