### ISSUE TITLE
Quick start sample code wrong output

### ISSUE THREAD

**Issue by Nikronic** [CSAILVision/semantic-segmentation-pytorch#158]
Hi,
I tried 
```bash
chmod +x demo_test.sh
./demo_test.sh
```
But the `.jpg` image and `.png` images are same. Actually, no segmentation happened on output image.

I am trying your code on google colab.

**Comment by hangzhaomit** [comment]
Shouldn't be, maybe you can check what happened here:
https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/test.py#L30

**Comment by Nikronic** [comment]
I've reviewed the code and it seems right, but I did not have enough time to check the numerical values. But I have got the same result. I will try to share a notebook with corresponding results.
Thank you

**Comment by Nikronic** [comment]
Sorry, you were right.
My browser problem!
