### ISSUE TITLE
Confusion on the batch_size in multi-gpu training

### ISSUE THREAD

**Issue by Dav-Jay** [CSAILVision/semantic-segmentation-pytorch#159]
Thanks the authors for your amazing work!

I'm confused on the setting of `batch_size` during training and wanna ask for further clarification. Please see my question below.

In `README`, it says:
> Now the batch size of a dataloader always equals to the number of GPUs, each element will be sent to a GPU. ...

So I understand the batch size during training is automatically set to be the number of GPUs. The line `batch_size=len(args.gpus)` in [L171 of train.py](https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/c80045b6723c86846f03855ecfe1f7a564331dad/train.py#L171) seems also prove this. 

But in [L166 of train.py](https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/c80045b6723c86846f03855ecfe1f7a564331dad/train.py#L166), I read `batch_per_gpu=args.batch_size_per_gpu` and the later has a default value of `2`. What's the purpose of using `batch_per_gpu` if as said above, the batch size is automatically set to be #GPUs? Thank you!

**Comment by Michriko** [comment]
if I understood it correctly the actual batchsize is the number of GPUs times the `batch_per_gpu` . 
e.g. 8 GPUs, `batch_per_gpu` of 4 is an batch_size of 32.

**Comment by Dav-Jay** [comment]
@Michriko thanks for reply! Could the authors @hangzhaomit @Tete-Xiao @metalbubble please confirm? Thanks!

**Comment by hangzhaomit** [comment]
@Dav-Jay Yes, that is correct.
