### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by sameer56** [CSAILVision/semantic-segmentation-pytorch#164]
Hi,
Can i get the steps for training on custom dataset which has 40 classes and data distribution is 7000 images for training and 1000 images for validation.

**Comment by komms** [comment]
make your own **.odgt** files for train and validation on your dataset and then change the **args** accordingly and then train the network

**Comment by mdt48** [comment]
@sameer56 @komms Hi, I was wondering if you could go into more detail in your response as I am new .  I have created an .odgt file for my dataset but what do you mean by changing the args?
