### ISSUE TITLE
checkpoint does not exitst

### ISSUE THREAD

**Issue by manza-ari** [CSAILVision/semantic-segmentation-pytorch#169]
how to fix this error:

File "test.py", line 177, in <module>
    os.path.exists(args.weights_encoder), 'checkpoint does not exitst!'
AssertionError: checkpoint does not exitst!

**Comment by komms** [comment]
The algorithm needs weights to run. Path to trained weights should be included as argument parser needs it.

**Comment by anandravi24** [comment]
You need to provide the suffix argument for test.py 
For Example - for baseline-resnet101dilated-ppm_deepsup
--suffix _epoch_25.pth

**Comment by hangzhaomit** [comment]
@manza-ari 
I have updated the repo with config files, so now there is less pain in inputting arguments.
