### ISSUE TITLE
Download paths no longer exist

### ISSUE THREAD

**Issue by vinhngx** [CSAILVision/semantic-segmentation-pytorch#177]
Download paths in download_ADE20k.sh and demo_test.sh no longer exist.

**Comment by hangzhaomit** [comment]
Hi @vinhngx , our server was under maintenance, they should work now.

**Comment by eaidova** [comment]
Hi @hangzhaomit , looks like your server is down again. Is it expected?
I tried to go http://sceneparsing.csail.mit.edu/ and my connection aborted by timeout.
Could you please say when it will be fixed?

Thank you for awesome project!
