### ISSUE TITLE
URL link to pretrained model can't be reached

### ISSUE THREAD

**Issue by IgnatiusIwanDJ** [CSAILVision/semantic-segmentation-pytorch#180]
Hey,I can not reach this url: sceneparsing.csail.mit.edu/model/pytorch it gives error 502: Server hangup, is the server still under maintenance ? also, is the pretrained weights to resnext-101 still available?

**Comment by hangzhaomit** [comment]
Thanks for reporting the error, just fixed.
Sorry we do not have resnext model yet.
