### ISSUE TITLE
it will execute multiple times when import from test.py

### ISSUE THREAD

**Issue by acdzh** [CSAILVision/semantic-segmentation-pytorch#186]
In my commamd line, the 'test.py' works well .

I want use this file in other python file, So I add a function to 'test.py', it is:

```python
    def run(self, imgs=None, model="config/ade20k-resnet50dilated-ppm_deepsup.yaml", gpu=0):
        if imgs == None:
            return False
        cfg.merge_from_file(model)

        cfg.MODEL.arch_encoder = cfg.MODEL.arch_encoder.lower()
        cfg.MODEL.arch_decoder = cfg.MODEL.arch_decoder.lower()

        # absolute paths of model weights
        cfg.MODEL.weights_encoder = os.path.join(
            cfg.DIR, 'encoder' + cfg.TEST.suffix)
        cfg.MODEL.weights_decoder = os.path.join(
            cfg.DIR, 'decoder' + cfg.TEST.suffix)

        if not os.path.exists(cfg.MODEL.weights_encoder):
            return  (False, "checkpoint does not exitst!")

        # generate testing image list
        if os.path.isdir(imgs[0]):
            imgs = find_recursive(imgs[0])
        else:
            imgs = [imgs]
        assert len(imgs), "imgs should be a path to image (.jpg) or directory."
        cfg.list_test = [{'fpath_img': x} for x in imgs]
        if not os.path.isdir(cfg.TEST.result):
            os.makedirs(cfg.TEST.result)
        
        main(cfg, gpu)
```

However, In another file, when I use this function like this:

```python
import run from test
run("test.jpg")
```

It outputs error:

```sh
Loading weights for net_encoder
Loading weights for net_decoder
# samples: 1
Loading weights for net_encoder
Loading weights for net_encoder
Loading weights for net_encoder
Loading weights for net_encoder
Loading weights for net_encoder
Loading weights for net_decoder
Loading weights for net_decoder
Loading weights for net_decoder
# samples: 1
Loading weights for net_decoder
Loading weights for net_decoder
# samples: 1
# samples: 1
# samples: 1
......
```

then my command line is crash.

However, to use this function in the file test.py works well. Only in other file will it failed.

This function is as same as the code in the  `if __name__ == '__main__':`, so where is wrong?

Thanks.

**Comment by hangzhaomit** [comment]
@acdzh 
maybe I have a bug here, can you try to replace ```imgs[0]``` with ```imgs```?

**Comment by acdzh** [comment]
> @acdzh
> maybe I have a bug here, can you try to replace `imgs[0]` with `imgs`?

Thanks for your help.
It does not work. And  I try print the `cfg.list_test` in those two ways (my function and the code in the `if __name__ == '__main__':`), they are the same (type and value).

**Comment by acdzh** [comment]
supplement:

1. the function is right.
2.  use this function in the `if __name__ == '__main__':` in the file `test.py` : works.
3. use this function in the out of  `if __name__ == '__main__':` in the file `test.py` : ERROR
4. use this function in other file after import: ERROR

**Comment by acdzh** [comment]
I finally find why:
I try to print the `__name__` in the begin of the function `run()`. At first it print `__main__`, after that it print many `__mp_main__`. It is the module `multiprocess `'s problem and only occurs on **Windows**.

Those too many new processes is the reason why my cammand line crash.

**Solution**:  in other file, please judge `if __name__ == '__main__':` every time, like this:

```python
import run from test
if __name__ == '__main__':
    run('img/test.jpg')
```

This problem just occurs on **Windows**.

For more can see [multiprocess](http://www.liujiangblog.com/course/python/82) , [torch.multiprocessing](https://blog.csdn.net/u013818990/article/details/79449186)

**Comment by jeewa985** [comment]
@acdzh  did you able to run the test.py for list of images in a folder. If so could you please let me know.
Thank you

**Comment by acdzh** [comment]
i success run it for an image, and i don not test if it will work for a list of images in a folder, but i think it may success to

**Comment by acdzh** [comment]
@jeewa985 
i success run it for an image, and i don not test if it will work for a list of images in a folder, but i think it may success, too

**Comment by dinimar** [comment]
@acdzh Could you please share your environment setup (Python version, pip list) ?
