### ISSUE TITLE
How to generate information like object150_info.csv

### ISSUE THREAD

**Issue by changlinzhang** [CSAILVision/semantic-segmentation-pytorch#19]
Hi,
I want generate all names of 150 classes, object names of each class, and number of pictures which contain this class. How can I do that? or how to generate information like object150.csv?

**Comment by chccgiven** [comment]
@hangzhaomit 
Hello!
I wonder whether the object150.csv will be used when training or testing? If I have to prepare the .csv file when I want to train on my own dataset?
Thank you.
