### ISSUE TITLE
run test for all images in a folder

### ISSUE THREAD

**Issue by Xiwang-pge** [CSAILVision/semantic-segmentation-pytorch#194]
Hi, I tried to run testing for the images in a folder. I specified the 
```
TEST_IMG= ./img_folder/

python3 -u test.py \
  --imgs $TEST_IMG \
```
When I run the test script, it gave me an error: test.py: error: 
```
argument --imgs: expected one argument
```
Any idea about this?
Thank you.

**Comment by Xiwang-pge** [comment]
Solved, just specify the folder and match the "extension" in find_recursive with the extensions of my images. 

Thank you.

**Comment by jeewa985** [comment]
@Xiwang-pge
Jeewan here. I'm struggling test for list of images. whene ever I specify the directory which includes the test image list gave me a error message "isADirectoryError" Could you please elaborate how did you overcome this issue. 
Thanks a lot.

**Comment by Xiwang-pge** [comment]
I used the code I posted above. The error I got is about the extension of my images. I need to convert the extension of all my images to ".JPG", then the code ran successfully.

**Comment by Xiwang-pge** [comment]
I used the code I posted above. The error I got is about the extension of my images. I need to convert the extension of all my images to ".JPG", then the code ran successfully.

**Comment by jeewa985** [comment]
@Xiwang-pge 
Thank you very much for the response and I do have all my images in .JPG format already. Did you made any changes to the test.py available in the following link.

https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/test.py

Best regards
