### ISSUE TITLE
Use of custom data set

### ISSUE THREAD

**Issue by jeewa985** [CSAILVision/semantic-segmentation-pytorch#196]
![Segmentation4](https://user-images.githubusercontent.com/54048772/65934056-f295db00-e44e-11e9-9779-c4e6925b9311.JPG)
Thank you very much for your code and informative explanations.  I have successfully trained and validated ADE20K data set using your code. 
However, when I tried to use the code for my own data set including four classes with 37 images (all are in same dimensions with 512*512) and 10 images for validation. I have made the data set according to ADE format.
Does anyone encoutered same issue ?
Your comments on this regard is highly appeciated

**Comment by adityashrm21** [comment]
There seems to be a problem in your json odgt file. Can you paste a snippet from it or the whole file?

**Comment by bzhao-1** [comment]
How did you solve this issue? I have about 200 images and 29 classes.
