### ISSUE TITLE
Error using custom data set

### ISSUE THREAD

**Issue by jeewa985** [CSAILVision/semantic-segmentation-pytorch#198]
I have encountered an error during evaluation for my own data set. anyone`s comments and suggestions on the following regard is highly appreciated.
![Segmenatation_6](https://user-images.githubusercontent.com/54048772/66281882-388fea80-e8f8-11e9-917f-66e33b2fdbf4.JPG)

**Comment by jeewa985** [comment]
I have checked the shape of img, seg_color and pre_clorwhich are not same. seg_color and and pred_color only having one row it seems. 
training phase was successfully completed with about 100% accuracy. any commnets or suggestions on this is highly appreciated.
![Segmenatation_7](https://user-images.githubusercontent.com/54048772/66285591-6846ee80-e908-11e9-8dab-efc77fdc5234.JPG)

**Comment by jeewa985** [comment]
@sainatarajan 

custom dataset:
1. create respective annotations images in gray scale including class indexes 
2. Make your own .odgt files for train and validation on your dataset.

Changes in code: 
1. Nothing much but you have to change .yaml file inside your config folder accordingly. 

Hope this helps

**Comment by simaiden** [comment]
> @sainatarajan
> 
> custom dataset:
> 
>     1. create respective annotations images in gray scale including class indexes
> 
>     2. Make your own .odgt files for train and validation on your dataset.
> 
> 
> Changes in code:
> 
>     1. Nothing much but you have to change .yaml file inside your config folder accordingly.
> 
> 
> Hope this helps

Can you help me with the annotations images? I don't understand how can labelling the different classes using only one gray scale image, and also where i have to put the class indexes.

Thanks!
