### ISSUE TITLE
training stopped..

### ISSUE THREAD

**Issue by MyoungHaSong** [CSAILVision/semantic-segmentation-pytorch#213]
I run this code.
python3 train.py --gpus 0,1  --cfg config/ade20k-resnet101-upernet.yaml

but training was stopped..

![image](https://user-images.githubusercontent.com/28686925/72323225-87190600-36eb-11ea-929c-0329988e8427.png)

my environment is nvidia-docker  + titan XP * 2 , CPU =i9-9900K
what should I do ?

**Comment by hangzhaomit** [comment]
Should be a GPU memory issue. Try adjust batch size.
