### ISSUE TITLE
Issue with PPM Decoder Code: BN Layer in the code doesn't work with 1x1 resolution input.

### ISSUE THREAD

**Issue by rishab-sharma** [CSAILVision/semantic-segmentation-pytorch#221]
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1, 1])

I tried to use the code of your PPM Decoder without DeepSup with a Resnet50 encoder...It breaks at 
pool_scale(conv5)

Where one of the scales leads to 1x1 map, followed by a BN.

This is resolved by making the net.eval() call, but what to do during training?

**Comment by daveboat** [comment]
I have this problem as well. Did you manage to resolve it?
