### ISSUE TITLE
ADE20k 150 Challenge instance segmentation

### ISSUE THREAD

**Issue by darleybarreto** [CSAILVision/semantic-segmentation-pytorch#223]
Hi,

Is it possible to get the original image (RGB masks) for the gray scale masks in the challenge, like a mapping of file names? I want to use them to create bounding boxes.

Thank you for your time.

**Comment by hangzhaomit** [comment]
https://docs.google.com/spreadsheets/d/1se8YEtb2detS7OuPE86fXGyD269pMycAWe2mtKUj2W8/edit?usp=sharing
Are you referring to the color mapping?

**Comment by darleybarreto** [comment]
In [this](https://github.com/CSAILVision/sceneparsing/tree/master/convertFromADE) folder you have code for converting a raw instance segmentation image (RGB), where R and G are related to the global class label and the B to the instance itself. We have in ADE20k 150 these converted raw targets, which I cannot recover the instance number, so would you happen to have some sort of document mapping from the classes segmentation (targets in ADE20k 150) to the original RGB image (on the complete ADE)?

Regards.

**Comment by carhartt21** [comment]
I don't think it's possible to generate the instances from the semantic segmentation labels.
The conversion works only in one way.  
But why don't you use the labels from the complete ADE data set right away?

**Comment by darleybarreto** [comment]
I wanted the ADE20K 150 because it is widely used, thus I would have models to use as baseline for comparison.

**Comment by hangzhaomit** [comment]
Hi @darleybarreto 
Not all object have instances, as some of them are stuff (background). So the conversion is not very straightforward.
Here is a subset I cleaned, with 100 classes with instances.
https://github.com/CSAILVision/placeschallenge/tree/master/instancesegmentation

**Comment by darleybarreto** [comment]
Oh, thank you so much for your quick response :smiley: . I guess this solves my problem!
