### ISSUE TITLE
access to pre-trained models

### ISSUE THREAD

**Issue by vladimir-dudnik** [CSAILVision/semantic-segmentation-pytorch#259]
It seems link [http://sceneparsing.csail.mit.edu/model/pytorch](http://sceneparsing.csail.mit.edu/model/pytorch) to pre-trained models does not work.
Was access to the model removed intentionally or this is a temporal issue?

**Comment by vladimir-dudnik** [comment]
Well, issue seems to be resolved, so I'll close this. Thanks you guys for all great work you are doing and sharing with community! We are demonstrating how models you have developed can be inferred on Intel OpenVINO, that's why we are interested in access to pre-trained models with permissive license.

**Comment by hangzhaomit** [comment]
Thanks for your efforts, we really appreciate it. @vladimir-dudnik
