### ISSUE TITLE
undefined name 'conv_out' in models.py

### ISSUE THREAD

**Issue by cclauss** [CSAILVision/semantic-segmentation-pytorch#27]
flake8 testing of https://github.com/CSAILVision/semantic-segmentation-pytorch on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./models.py:330:17: F821 undefined name 'conv_out'
        conv5 = conv_out[-1]
                ^
1     F821 undefined name 'conv_out'
```

**Comment by Tete-Xiao** [comment]
Sorry it's a typo. We have fixed it in the master branch.
