### ISSUE TITLE
Can't download the pre trained models

### ISSUE THREAD

**Issue by MSDuran** [CSAILVision/semantic-segmentation-pytorch#272]
Could you please share the pre-trained model files because I can not connect to the website?

**Comment by noobmaster29** [comment]
I'm having the same issue. The first cell in the colab demo is also hanging when run.

**Comment by subramanyakrishna** [comment]
Yes Please resolve this

**Comment by subramanyakrishna** [comment]
http://sceneparsing.csail.mit.edu/model/pytorch/ade20k-resnet50dilated-ppm_deepsup/encoder_epoch_20.pth this link is not working

**Comment by rayeeed** [comment]
http://sceneparsing.csail.mit.edu/ this website is down completely. Its weird because other csail.mit.edu websites are working. My thesis work is basically screwed if I don't get the  pre-trained model files.

**Comment by subramanyakrishna** [comment]
https://colab.research.google.com/drive/17alEj52QYGNB1sxNFL96BoaI-weMnpYM?usp=sharing 
You can use the above method for semantic segmentation  if you want, Hope it helps

**Comment by rayeeed** [comment]
https://www.kaggle.com/d0blee2/starter-superpoint-pytorch-e9ca99d4-6 

go to input>superpoint pytorch>superpoint pytorch>models. All the weights are saved there. I took the resnet50 decoder and encoder; tried it in [this pretrained model](https://colab.research.google.com/github/CSAILVision/semantic-segmentation-pytorch/blob/master/notebooks/DemoSegmenter.ipynb) and it is producing correct segmentation.

**Comment by subramanyakrishna** [comment]
Oh Thank you
