### ISSUE TITLE
Can't use cuda.

### ISSUE THREAD

**Issue by zhiweifang** [CSAILVision/semantic-segmentation-pytorch#31]
Hi, 
I use `conda install -c prigoyal pytorch=0.4.0`  to install pytorch and run `./demo_test.sh`.
Everything goes well until line 105 of test.py:
```
segmentation_module.cuda()
```
The output is:
```
 ./demo_test.sh: line 30: 27040 Segmentation fault      (core dumped) python3 -u test.py --model_path $MODEL_PATH --test_img $TEST_IMG --arch_encoder resnet50_dilated8 --arch_decoder ppm_bilinear_deepsup --fc_dim 2048 --result $RESULT_PATH
```
I guess it's the problem of pytorch, and test the code:
```
import torch
x = torch.Tensor(3,3)
x.cuda()
```
Similar error : `Segmentation fault (core dumped)`.

Any suggestions?

BTW, my other projects of pytorch 0.2.0 and 0.3.0 on this machine work well.

Thanks.

**Comment by Tete-Xiao** [comment]
Hi,

Based on the third segment of your codes, I'm pretty sure it's something related to your machine, or the PyTorch you are using.

Try building and compiling from source. If it doesn't work, there's probably something wrong with your device that is not compatible with PyTorch. I'm afraid we can't fix this for your.

Best,

**Comment by hangzhaomit** [comment]
I just tested on the most recent Pytorch from prigoyal, it is failing as well. Then build from source might be the best solution. @zhiweifang

**Comment by zhiweifang** [comment]
Thanks. @Tete-Xiao @hangzhaomit 
I build from source and now everything goes well.
btw，there are two warnings：
```
functional.py:1762:UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
```
```
train.py:71: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  history['train']['acc'].append(acc.data[0])
```

**Comment by littlebelly** [comment]
Using pytorch 0.4.0 from ostrokach, it can work fine on my machine.

conda install -c ostrokach-forge pytorch

**Comment by hangzhaomit** [comment]
@littlebelly Thanks for your input, it works.

**Comment by Tete-Xiao** [comment]
@zhiweifang  It is because PyTorch's source codes are still being aggressively changed...

We tried to catch up with the latest source codes, but realized that if we use the newest codes, it doesn't work on any older version...

We will update and fix warnings when a stable version of PyTorch is released.
