### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by dongdonghy** [CSAILVision/semantic-segmentation-pytorch#35]
When I run the test.py, I got:

Namespace(arch_decoder='ppm_bilinear_deepsup', arch_encoder='resnet50_dilated8', batch_size=1, fc_dim=2048, gpu_id=0, imgMaxSize=1000, imgSize=[300, 400, 500, 600], model_path='baseline-resnet50_dilated8-ppm_bilinear_deepsup/', num_class=150, num_val=-1, padding_constant=8, result='./', segm_downsampling_rate=8, suffix='_epoch_20.pth', test_img='ADE_val_00001519.jpg')
baseline-resnet50_dilated8-ppm_bilinear_deepsup/encoder_epoch_20.pth
Loading weights for net_encoder
Loading weights for net_decoder
samples: 1
Segmentation fault (core dumped)

I have 2*E5 CPU and 2*NVIDIA Tian xp GPU.
Any idea?
Thanks!

**Comment by Tete-Xiao** [comment]
#31 
See if it helps.

**Comment by dongdonghy** [comment]
It works now. Thanks!
