### ISSUE TITLE
Can you share the ResNet101 pretrained model?

### ISSUE THREAD

**Issue by PkuRainBow** [CSAILVision/semantic-segmentation-pytorch#37]
Hi, great project.

I find  the link of the pretrained models do not contain the ResNet-101(replace the 7X7 conv with 3 3X3 conv) model.
the url you provide is valid .....

http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet101-imagenet.pth

Could you share us when it will be convenient for you to share the model?

**Comment by Tete-Xiao** [comment]
Please check out the latest version of this repo.

**Comment by PkuRainBow** [comment]
@Tete-Xiao Hi, tete. It seems that network resnet.py is not consistent with the released checkpoints.

```
        self.conv1 = conv3x3(3, 64, stride=2)
        self.bn1 = BatchNorm2d(64)
        self.relu1 = nn.ReLU(inplace=False)
        self.conv2 = conv3x3(64, 64)
        self.bn2 = BatchNorm2d(64)
        self.relu2 = nn.ReLU(inplace=False)
        self.conv3 = conv3x3(64, 128)
        self.bn3 = BatchNorm2d(128)
        self.relu3 = nn.ReLU(inplace=False)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)

        self.layer1 = self._make_layer(block, 64, layers[0])
```

After conv3+bn3+relu3, the features' channel is 128 but the layer1 is dealing with input of channel 64.

I got the follow bug 🚔 

> RuntimeError: While copying the parameter named layer1.0.conv1.weight, whose dimensions in the model are torch.Size([64, 64, 1, 1]) and whose dimensions in the checkpoint are torch.Size([64, 128, 1, 1]).
