### ISSUE TITLE
Look forward to the new arxiv paper

### ISSUE THREAD

**Issue by kuonangzhe** [CSAILVision/semantic-segmentation-pytorch#38]
Thanks for the awesome work! I am also looking forward to the new paper, Unified Perceptual Parsing for Scene Understanding. Hope that it could be avalible soon. 

Thanks a lot!

**Comment by zimenglan-sysu-512** [comment]
+1

**Comment by Tete-Xiao** [comment]
Please check out this [link](https://arxiv.org/abs/1807.10221) for arxiv paper!
