### ISSUE TITLE
Train on CityScapes

### ISSUE THREAD

**Issue by CarryJzzZ** [CSAILVision/semantic-segmentation-pytorch#45]
Hi, @cvondrick @quantombone @metalbubble @hangzhaomit ,
I want to train this model on CityScapes. I must to modify the `TrainDataset` for the fixed size of cityscapes image. But there is no `train.odgt` about cityscapes, and I think it is not necessary for cityscapes. 
I am not sure that If I use this code, whether the inputs crossed multi-gpu is a different mini-batch. 
`class cityscapes(Dataset):

    def __init__(self, root, co_transform=None, subset='train'):
        self.images_root = os.path.join(root, 'leftImg8bit/')
        self.labels_root = os.path.join(root, 'gtFine/')
        
        self.images_root += subset
        self.labels_root += subset

        print (self.images_root)
        #self.filenames = [image_basename(f) for f in os.listdir(self.images_root) if is_image(f)]
        self.filenames = [os.path.join(dp, f) for dp, dn, fn in os.walk(os.path.expanduser(self.images_root)) for f in fn if is_image(f)]
        self.filenames.sort()

        #[os.path.join(dp, f) for dp, dn, fn in os.walk(os.path.expanduser(".")) for f in fn]
        #self.filenamesGt = [image_basename(f) for f in os.listdir(self.labels_root) if is_image(f)]
        self.filenamesGt = [os.path.join(dp, f) for dp, dn, fn in os.walk(os.path.expanduser(self.labels_root)) for f in fn if is_label(f)]
        self.filenamesGt.sort()

        self.co_transform = co_transform 

    def __getitem__(self, index):
        filename = self.filenames[index]
        filenameGt = self.filenamesGt[index]

        with open(image_path_city(self.images_root, filename), 'rb') as f:
            image = load_image(f).convert('RGB')
        with open(image_path_city(self.labels_root, filenameGt), 'rb') as f:
            label = load_image(f).convert('P')

        if self.co_transform is not None:
            image, label = self.co_transform(image, label)

        return image, label

    def __len__(self):
        return len(self.filenames)`
Can you give me some advice.
Thanks a lot!

**Comment by Tete-Xiao** [comment]
No you are doing the wrong way. You can read README.md carefully for the reason. Or in short, you shouldn't use the variable "index" in __getitem__ at all.

My recommendation is to create the odgts yourself on other datasets. Just read some line in our odgts and find out the formats, and create your own. You can even write the codes in IPython. It wouldn't take more than a few minutes.

**Comment by pm-2019** [comment]
Someone can post the code to write the odgt file for a different dabatase?
Thanks!

**Comment by pm-2019** [comment]
Someone can post the code to write the odgt file for a different dabatase?
Thanks!
