### ISSUE TITLE
Evaluate with multi GPU and mini batch

### ISSUE THREAD

**Issue by WayneZww** [CSAILVision/semantic-segmentation-pytorch#48]
Hi all,
I found that this code still does not implement evaluation on multi GPU, I have tried the same manner as in train.py, but meet infinite recursioon problem during forwad propagation with data_parallel.py.
Hope somebody could help, or will the evaluation using multi GPU will be supported?

**Comment by WayneZww** [comment]
Okay, I'm looking forward for that!

**Comment by Tete-Xiao** [comment]
Hi,
Please check out the latest version of this repo. You'll find what you want :)
