### ISSUE TITLE
RuntimeError: While copying the parameter named layer1.0.conv1.weight

### ISSUE THREAD

**Issue by PkuRainBow** [CSAILVision/semantic-segmentation-pytorch#50]
@Tete-Xiao Hi, tete. It seems that network resnet.py is not consistent with the released checkpoints.

```
        self.conv1 = conv3x3(3, 64, stride=2)
        self.bn1 = BatchNorm2d(64)
        self.relu1 = nn.ReLU(inplace=False)
        self.conv2 = conv3x3(64, 64)
        self.bn2 = BatchNorm2d(64)
        self.relu2 = nn.ReLU(inplace=False)
        self.conv3 = conv3x3(64, 128)
        self.bn3 = BatchNorm2d(128)
        self.relu3 = nn.ReLU(inplace=False)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)

        self.layer1 = self._make_layer(block, 64, layers[0])
```

After conv3+bn3+relu3, the features' channel is 128 but the layer1 is dealing with input of channel 64.

I got the follow bug 🚔 

> RuntimeError: While copying the parameter named layer1.0.conv1.weight, whose dimensions in the model are torch.Size([64, 64, 1, 1]) and whose dimensions in the checkpoint are torch.Size([64, 128, 1, 1]).

**Comment by Tete-Xiao** [comment]
It works perfectly fine on my and others' servers. And I've checked the md5 sum. The models on the CSAIL's server are the same ones on my server. 

You may need to download a new model and check out whether you get the models or the codes wrong.

**Comment by PkuRainBow** [comment]
@Tete-Xiao Thanks, I have solved problem.

**Comment by johnathanchiu** [comment]
How did you solve this issue?

**Comment by sbelharbi** [comment]
same issue as @PkuRainBow 
The loaded weights mismatch the defined resnet architecture...
@PkuRainBow how did you fix it? thanks!
