### ISSUE TITLE
The error while test

### ISSUE THREAD

**Issue by B-IU** [CSAILVision/semantic-segmentation-pytorch#52]
os.path.exists(args.weights_encoder), 'checkpoint does not exitst!
AssertionError: checkpoint does not exitst!`

I use the command      python test.py --test_img ADE_val_00001519.jpg --model_path `./ckpt/baseline-resnet50_dilated8-ppm_bilinear_deepsup-ngpus2-batchSize8-imgMaxSize384-paddingConst8-segmDownsampleRate8-LR_encoder0.02-LR_decoder0.02-epoch20-decay0.0001-fixBN0/` --suffix _epoch20.pth
both encoder and decoder have been trained,why does this error happen and how should I solve this problem?

**Comment by Tete-Xiao** [comment]
_epoch_20.pth  ...

**Comment by B-IU** [comment]
.....hahahahhh..................
