### ISSUE TITLE
Training using parts too

### ISSUE THREAD

**Issue by rnditdev** [CSAILVision/semantic-segmentation-pytorch#56]
Is it planned to use part segments to improve the granularity of the detected classes?
Thank you.

**Comment by Tete-Xiao** [comment]
Thanks for your interests in our work. The arxiv paper to be released will describe such framework that jointly segments parts and objects. The codes will be released, although it may take some time.

**Comment by hangzhaomit** [comment]
@rnditdev 
Please check out our repo:
https://github.com/CSAILVision/unifiedparsing
