### ISSUE TITLE
Use of scipy imresize function

### ISSUE THREAD

**Issue by heinzermch** [CSAILVision/semantic-segmentation-pytorch#61]
The use of the imresize function from scipy.misc in dataset.py (line 130) is highly problematic in my opinion. It changes the range of values from [0,n] to [0,255]. In my case n was rather small, less than 10. And it lead to an error in a CUDA assumption later on, it took me 3 hours to track down the error.

It looks like you somehow address the issue in the next lines, but that method is not stable when changing the number of classes.

**Comment by Tete-Xiao** [comment]
In another project, I've used the same codes for several different class numbers, and it works perfectly fine.

One tricky part is to correctly understand what the image processing library does. For image resizing with nearest neighbor, you need to make sure that the value of each channel is within [0, 255]. If you'd like to resize a segmentation map with more than 255 classes, you need to encode the number to three different channels, resize, and decode it to the class index. You need to make sure that the type is uint8.

I suggest you review your code and let me know when and where there'll be a problem.

**Comment by heinzermch** [comment]
The [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imresize.html) is pretty clear on change of range:

> This function uses bytescale under the hood to rescale images to **use the full (0, 255) range** if mode is one of None, 'L', 'P', 'l'. It will also cast data for 2-D images to uint32 for mode=None (which is the default).

I'm also not the first to discover that this can be an [issue](https://github.com/scipy/scipy/issues/4458).

Either way, the function is deprecated, the code should be updated.
