### ISSUE TITLE
pre-activated ResNet Bottleneck

### ISSUE THREAD

**Issue by akziq** [CSAILVision/semantic-segmentation-pytorch#65]
Have anyone tried   pre-activated ResNet  Bottleneck ?
Will it better than original  ResNet   in  Semantic Segmentation ?

![](https://user-images.githubusercontent.com/6086781/28494249-97e81166-6ef6-11e7-88b8-fa4aa184bc0b.png)
paper:
https://arxiv.org/pdf/1603.05027.pdf

**Comment by Tete-Xiao** [comment]
Sorry we haven't tried such models. You may try it yourself and share results with everybody :)
