### ISSUE TITLE
Accuracy drops / loss increases when creating a checkpoint

### ISSUE THREAD

**Issue by heinzermch** [CSAILVision/semantic-segmentation-pytorch#70]
Over the past couple of days I've observed multiple times that creating a checkpoint, or storing the model influences at least the reported performance:

> Epoch: [12][4860/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.012647, lr_decoder: 0.012647, Accuracy: 99.85, Loss: 0.006357, Time: 14:42:58
Epoch: [12][4880/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.012644, lr_decoder: 0.012644, Accuracy: 99.85, Loss: 0.006356, Time: 14:43:33
Epoch: [12][4900/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.012642, lr_decoder: 0.012642, Accuracy: 99.85, Loss: 0.006354, Time: 14:44:08
Epoch: [12][4920/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.012639, lr_decoder: 0.012639, Accuracy: 99.85, Loss: 0.006351, Time: 14:44:42
Epoch: [12][4940/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.012637, lr_decoder: 0.012637, Accuracy: 99.85, Loss: 0.006348, Time: 14:45:17
Epoch: [12][4960/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.012634, lr_decoder: 0.012634, **Accuracy: 99.85**, **Loss: 0.006362**, Time: 14:45:52
Epoch: [12][4980/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.012632, lr_decoder: 0.012632, **Accuracy: 99.85**, **Loss: 0.006389**, Time: 14:46:28
Saving checkpoints...
Epoch: [13][0/5000], Time: 1.74, Data: 0.00, lr_encoder: 0.012629, lr_decoder: 0.012629, **Accuracy: 99.65**, **Loss: 0.016540**, Time: 14:47:05
Epoch: [13][20/5000], Time: 1.76, Data: 0.09, lr_encoder: 0.012627, lr_decoder: 0.012627, **Accuracy: 99.40**, **Loss: 0.033453**, Time: 14:47:41
Epoch: [13][40/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.012624, lr_decoder: 0.012624, Accuracy: 99.39, Loss: 0.034062, Time: 14:48:15
Epoch: [13][60/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.012621, lr_decoder: 0.012621, Accuracy: 99.37, Loss: 0.035348, Time: 14:48:50
...
Epoch: [13][4960/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.012001, lr_decoder: 0.012001, **Accuracy: 99.77**, **Loss: 0.010920**, Time: 17:11:05
Epoch: [13][4980/5000], Time: 1.74, Data: 0.09, lr_encoder: 0.011998, lr_decoder: 0.011998, **Accuracy: 99.77**, **Loss: 0.010902**, Time: 17:11:40

It can then take more than an entire epoch to get back to the original level, any idea why this is happening?

**Comment by Tete-Xiao** [comment]
It is because we record averaged loss and accuracy for each epoch. The variation at the beginning of each epoch is large. The number would be unreliable at the first few iterations.

**Comment by pnzsl** [comment]
Can you tell me how the parameters in the **.yaml** file are set? So that you can train the image to such accuracy. If you can help me, I will be very grateful!
