### ISSUE TITLE
I want to pick up the camera. How can I change it?

### ISSUE THREAD

**Issue by ytgcljj** [CSAILVision/semantic-segmentation-pytorch#77]
I want to pick up the camera. How can I change it?

**Comment by hangzhaomit** [comment]
please specify your question

**Comment by ytgcljj** [comment]
Hello, I can use the picture now, but I have a USB camera in my hand. How can I operate it before I can use the camera?

**Comment by hangzhaomit** [comment]
Sorry your question is not related to segmentation.
