### ISSUE TITLE
problem occur during training（dataloader）

### ISSUE THREAD

**Issue by JonyFaker** [CSAILVision/semantic-segmentation-pytorch#80]
here is the error: **RuntimeError: DataLoader worker (pid 7948) exited unexpectedly with exit code 1**
my develop environment is：**2 1080 Ti gpus**，when train the model, I just follow steps about train(default) in README, **i set num_gpus == 2(1), batch_per_gpu == 1**, but , this problem occurs, i do not know how to solve this, hope your help!
Thanks!

**Comment by JonyFaker** [comment]
@metalbubble

**Comment by Tete-Xiao** [comment]
Unfortunately we're unable to help you because you need to provide us with actual error info other than error code.

**Comment by JonyFaker** [comment]
sorry，i knew the reason, because of the shared memory in docker
