### ISSUE TITLE
Why set label -1-149 rather than 0-150?

### ISSUE THREAD

**Issue by cuixiongwen** [CSAILVision/semantic-segmentation-pytorch#87]
I noticed  line149 in dataset.py :
batch_segms = batch_segms - 1 # label from -1 to 149.
Could someone tell me why set label -1-149 rather than 0-150?Thank you a lot.

**Comment by Tete-Xiao** [comment]
It doesn't matter at all. It's like I can't explain why OpenCV uses BRG while PIL uses RGB.
