### ISSUE TITLE
The meaning of epoch_iters.

### ISSUE THREAD

**Issue by MhLiao** [CSAILVision/semantic-segmentation-pytorch#89]
Thank you for your great code. 
I am puzzled about the epoch_iters in this line:
https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/24e13b30f1af9f8ae7fb80b5cace899be3d1794a/train.py#L244
Why is the epoch_iters irrelevant to batch size? How can we set it if the training data contains about 7 million images?

**Comment by Liuyixuan95** [comment]
I am also puzzled about this question.

**Comment by Tete-Xiao** [comment]
# of images in an epoch = epoch_iters * nr_gpus * images_per_gpu

**Comment by JetteKA** [comment]
But in that case, the epoch_iters is not irrelevant to the batch_size, is it? In the code it is explicitly stated that the number of iterations of each epoch is irrelevant to batch size. How can this be?
