### ISSUE TITLE
LABEL

### ISSUE THREAD

**Issue by BEYBB7** [CSAILVision/semantic-segmentation-pytorch#92]
Thanks for your work! I can't find where the sceneCategories.txt and objectInfo150.txt is used, and can you pay attention to explain the meaning of the train, val and ratio in objectInfo150.txt?Thank you very much!

**Comment by hangzhaomit** [comment]
They are for the users to understand the mapping between index and categories, but not used in the model training.
ratio = (the number of pixels of one category) / (the number of pixels of the dataset).
