### ISSUE TITLE
Extraction of encoded iformation

### ISSUE THREAD

**Issue by acecreamu** [CSAILVision/semantic-segmentation-pytorch#93]
Could advise how to extract encoded data? (For single image inference)

I tried modify directly:
```
#pred = self.decoder(self.encoder(feed_dict['img_data'], return_feature_maps=True), segSize=segSize)
pred = self.encoder(feed_dict['img_data'], return_feature_maps=True)
```
but it returns list of length 4, with arrays of different shapes inside...
What the shape of this encoded data originally? I need to obtain just a vector of deep features.

Thank you in advance.

**Comment by hangzhaomit** [comment]
@acecreamu 
These are exactly the deep features you want, you just need to resize them.
The reason for different sizes is that they come from different intermediate layers.
