### ISSUE TITLE
Further trainining the model on an extended dataset

### ISSUE THREAD

**Issue by jackureu** [CSAILVision/semantic-segmentation-pytorch#96]
Hi

I love your code and pretrained model and wanted to use it on a dataset that is a little bit different (Specifically images from a specific type of scenes).
Using your pretrained model, my results are pretty good, but I believe that if I will train it further on my images, I can get a model that generalizes better to my images.

I created a dataset of several (~500) images in the correct format, and wanted to take your full pretrained model and continue training it from that point on a combination of my dataset and the original ADE20k dataset (to avoid having it completely overfit my images).

Could you please suggest what could be the best way to do that?

I thought of taking the train.py script, modify it so it will first load the pretrained model.
Change the loader so it will load images from both datasets (with some probability or something similar)
and train it for a few epochs.

Any suggestion might help
Thanks

**Comment by hangzhaomit** [comment]
You are right :-)
