### ISSUE TITLE
About the multi-scale testing choices.

### ISSUE THREAD

**Issue by PkuRainBow** [CSAILVision/semantic-segmentation-pytorch#99]
Hi, I noticed that you set 

`parser.add_argument('--imgSize', default=[300,375,450,525,600], nargs='+', type=str,`

for multi-scale testing and achieve some performance improvement. However, I am wondering whether the original PSP use flip to further improve the performance?

**Comment by hangzhaomit** [comment]
Yes, the original PSPnet use overlapping crops(we did not), multi-scale and flipping during testing.
